### ISSUE TITLE
LCD and user button should be removed from final product

### ISSUE THREAD

**Issue by W0481966** [NSCC-workterm-treadmill-2023/treadmill-driver#7]
They're good for debugging and demoing, but they'll be out of sight and out of reach in the end.

**Comment by JayPankajPatel** [comment]
Hey I would like to work on this issue, I was wondering if I could get more details on the where in the code these interfaces are used

**Comment by W0481966** [comment]
Look for `BUTTON` for the button. The LCD is used in `displayIncline()` and `displaySpeedSensorTime()`, and of course `setup()` and the variable definitions up top.

**Comment by JayPankajPatel** [comment]
Do you think making a conditional compilation statement might be better just in case it might be needed again for debugging or should I just go ahead and remove it.

**Comment by JayPankajPatel** [comment]
Also could you assign the issue to me
